# apiVersion: v1
# kind: Service
# metadata:
#   name: arvigo-backend-service
#   labels:
#     app: arvigo-backend
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: arvigo-backend
#   type: LoadBalancer
#   loadBalancerIP: 34.101.205.212

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: arvigo-backend-workload
#   labels:
#    app: arvigo-backend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: arvigo-backend
#   template:
#     metadata:
#       labels:
#         app: arvigo-backend
#     spec:
#       containers:
#       - name: arvigo-backend-container
#         image: asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#           protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: arvigo-backend-service
  labels:
    app: arvigo-backend
spec:
  selector:
    app: arvigo-backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arvigo-backend-workload
  labels:
   app: arvigo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arvigo-backend
  template:
    metadata:
      labels:
        app: arvigo-backend
    spec:
      containers:
      - name: arvigo-backend-container
        image: asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP

---

 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: arvigo-backend-ingress
   annotations:
    kubernetes.io/ingress.global-static-ip-name: arvigo-ip-static-backend-global
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "gce"
 spec:
   rules:
   - host: api.arvigo.site
     http:
       paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: arvigo-backend-service
              port: 
                number: 80