apiVersion: v1
kind: Service
metadata:
  name: arvigo-backend-service
  labels:
    app: arvigo-backend
spec:
  selector:
    app: arvigo-backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer
  loadBalancerIP: 34.101.205.212
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arvigo-backend
  labels:
    app: arvigo-backend
spec:
  selector:
    matchLabels:
      app: arvigo-backend
  template:
    metadata:
      labels:
        app: arvigo-backend
    spec:
      containers:
      - name: arvigo-backend-container
        image: asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
        ports:
        - containerPort: 8080