# apiVersion: v1
# kind: Namespace
# metadata:
#   name: production
    
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: arvigo-backend
#   annotations: 
#     cloud.google.com/neg: '{"ingress": true}'
#   namespace: production
#   labels:
#     app: arvigo-backend
# spec:
#   selector:
#     app: arvigo-backend
#   ports:
#   - port: 80
#     protocol: TCP
#     name: http
#     targetPort: 80
#   type: NodePort

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: arvigo-backend
#   namespace: production
# spec:
#   selector:
#     matchLabels:
#       app: arvigo-backend
#   strategy:
#     type: RollingUpdate
#   template: #Template for container
#     metadata:
#       labels:
#         app: arvigo-backend
#     spec:
#       containers:
#       - name: arvigo-backend
#         image:  asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
#           name: arvigo-backend
#         resources:
#           requests:
#             cpu: 50m

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: arvigo-backend
#   namespace: production
#   annotations:
#     kubernetes.io/ingress.global-static-ip-name: arvigo-ip-ex-backend
#     kubernetes.io/ingress.allow-http: "true"
#     networking.gke.io/managed-certificates: arvigo-backend
# spec:
#   rules:
#     - host: api.arvigo.site
#       http:
#         paths:
#         - path: /*
#           pathType: ImplementationSpecific
#           backend:
#             service:
#               name: arvigo-backend
#               port: 
#                 number: 80

# ---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: arvigo-backend
#   namespace: production
# spec:
#   domains:
#     - api.arvigo.site

# apiVersion: v1
# kind: Service
# metadata:
#   name: arvigo-backend
#   labels:
#     app: arvigo-backend
# spec:
#   ports:
#   - port: 80
#     targetPort: 8080
#   selector:
#     app: arvigo-backend
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: arvigo-backend
  namespace: default
  annotations: 
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: arvigo-backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arvigo-backend
  namespace: default
spec:
  selector:
    matchLabels:
      run: arvigo-backend
  template:
    metadata:
      labels:
        run: arvigo-backend
    spec:
      containers:
      - image: asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
        imagePullPolicy: IfNotPresent
        name: arvigo-backend
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: arvigo-backend
      port:
        number: 80
# apiVersion: apps/v1
# kind: Deployment
#   name: web
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: arvigo-backend
#   template:
#     metadata:
#       labels:
#         app: arvigo-backend
#     spec:
#       containers:
#       - name: arvigo-backend
#         image: asia.gcr.io/$PROJECT_ID/production/arvigo-backend:$SHORT_SHA
#         imagePullPolicy: Always
#         ports:
#           - containerPort: 8080
#             name: arvigo-backend
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: arvigo-backend
#   annotations:
#     kubernetes.io/ingress.allow-http: "true"
#     kubernetes.io/ingress.global-static-ip-name: "arvigo-ip-ex-backend"
#     kubernetes.io/ingress.class: "gce"
# spec:
#   rules:
#   - host: api.arvigo.site
#     http:
#       paths:
#       - path: /*
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: arvigo-backend
#             port:
#               number: 80
